var lang = {
	get c() {
		return this[settings.get('lang')] || this.zh;
	},
	en: {
		MARK_AS_READ: 'Mark As (Un)Read',
		DELETE: 'Delete',
		UPDATE: 'Update',
		PRINT: 'Print',
		SEARCH: 'Search for...',
		SEARCH_TIP: 'Search articles. Use \':\' to search in content as well.',
		NEVER: 'Never',
		EVERY_5_MINUTES: 'Every 5 minutes',
		EVERY_15_MINUTES: 'Every 15 minutes',
		EVERY_30_MINUTES: 'Every 30 minutes',
		EVERY_HOUR: 'Every hour',
		EVERY_2_HOURS: 'Every 2 hours',
		EVERY_3_HOURS: 'Every 3 hours',
		EVERY_5_HOURS: 'Every 5 hours',
		EVERY_10_HOURS: 'Every 10 hours',
		EVERY_24_HOURS: 'Every 24 hours',
		EVERY_WEEK: 'Every week',
		USERNAME: 'Username',
		PASSWORD: 'Password',
		CANCEL: 'Cancel',
		OK: 'OK',
		LAYOUT: 'Layout',
		LINES: 'Lines',
		SORT_ORDER: 'Sort Order',
		DESCENDING: 'Descending',
		ASCENDING: 'Ascending',
		ONE_LINE: 'One-Line',
		TWO_LINES: 'Two-Lines',
		AUTO: 'Auto',
		FULL_ARTICLE: 'Full article',
		REALLY_DELETE: 'Do you really want to delete this feed?',
		ALL_FEEDS: 'All feeds',
		PINNED: 'Pinned',
		TRASH: 'Trash',
		MARK_ALL_AS_READ: 'Mark All As Read',
		PROPERTIES: 'Properties',
		UNDELETE: 'Undelete',
		NEXT_UNREAD: 'Next Unread',
		PREV_UNREAD: 'Previous Unread',
		MARK_AND_NEXT_UNREAD: 'Mark And Next Unread',
		MARK_AND_PREV_UNREAD: 'Mark And Prev Unread',
		PIN: '(Un)Pin',
		PIN_QUESTION_A: 'Item "',
		PIN_QUESTION_B: '" is pinned. Do you really want to delete it?',
		MARK_ALL_QUESTION: 'Do you really want to mark ALL articles as read?',
		ADD_RSS_SOURCE: 'Add RSS Source',
		UPDATE_ALL: 'Update all',
		FETCH_TITLE_TIP: 'If this field is empty, the title of the feed will be used instead.',
		NAME: 'Name',
		ADDRESS: 'Address',
		JANUARY: 'January',
		FEBRUARY: 'February',
		MARCH: 'March',
		APRIL: 'April',
		MAY: 'May',
		JUNE: 'June',
		JULY: 'July',
		AUGUST: 'August',
		SEPTEMBER: 'Semptember',
		OCTOBER: 'October',
		NOVEMBER: 'November',
		DECEMBER: 'December',
		MONDAY: 'Monday',
		TUESDAY: 'Tuesday',
		WEDNESDAY: 'Wednesday',
		THURSDAY: 'Thursday',
		FRIDAY: 'Friday',
		SATURDAY: 'Saturday',
		SUNDAY: 'Sunday',
		TODAY: 'Today',
		YESTERDAY: 'Yesterday',
		LAST_WEEK: 'Last Week',
		EARLIER_THIS_MONTH: 'Earlier This Month',
		MORE: 'More',
		SETTINGS: 'Settings',
		EMPTY_TRASH: 'Empty Trash',
		RSS_FEED_URL: 'RSS Feed URL: ',
		OPTIONS: 'Options',
		UPDATING_FEEDS: 'Updating feeds',

		UNREAD: 'unread',
		TOTAL: 'total',
		NEW_FOLDER: 'New Folder',
		DOWNLOAD: 'Download',
		DELETE_ALL_ARTICLES: 'Delete All Articles',
		DELETE_ALL_Q: 'Do you really want to comletely delete ALL articles?',
		REALLY_EMPTY_TRASH: 'Do you really want to completely delete all articles from trash?',
		RENAME: '重命名',
		FOLDER_NAME: '文件夹名'
	},
	zh: {
		MARK_AS_READ: '标记(未读)已读',
		DELETE: '删除',
		UPDATE: '更新',
		PRINT: '打印',
		SEARCH: '搜索...',
		SEARCH_TIP: 'Search articles. Use \':\' to search in content as well.',
		NEVER: '从不',
		EVERY_5_MINUTES: '每 5 分钟',
		EVERY_15_MINUTES: '每 15 分钟',
		EVERY_30_MINUTES: '每 30 分钟',
		EVERY_HOUR: '每 1 小时',
		EVERY_2_HOURS: '每 2 小时',
		EVERY_3_HOURS: '每 3 小时',
		EVERY_5_HOURS: '每 5 小时',
		EVERY_10_HOURS: '每 10 小时',
		EVERY_24_HOURS: '每 24 小时',
		EVERY_WEEK: '每周',
		USERNAME: '用户名',
		PASSWORD: '密码',
		CANCEL: '退出',
		OK: '确定',
		LAYOUT: 'Layout',
		LINES: 'Lines',
		SORT_ORDER: 'Sort Order',
		DESCENDING: 'Descending',
		ASCENDING: 'Ascending',
		ONE_LINE: 'One-Line',
		TWO_LINES: 'Two-Lines',
		AUTO: '自动',
		FULL_ARTICLE: '全部文章',
		REALLY_DELETE: '确定删除?',
		ALL_FEEDS: '所有',
		PINNED: '标记',
		TRASH: '回收站',
		MARK_ALL_AS_READ: '标记全部为已读',
		PROPERTIES: '属性',
		UNDELETE: '撤销删除',
		NEXT_UNREAD: '转到下一篇未读',
		PREV_UNREAD: '转到上一篇未读',
		MARK_AND_NEXT_UNREAD: '标记为已读并转到下一篇未读',
		MARK_AND_PREV_UNREAD: '标记为已读并转到上一篇未读',
		PIN: '(Un)Pin',
		PIN_QUESTION_A: 'Item "',
		PIN_QUESTION_B: '" 被选中. 确定删除?',
		MARK_ALL_QUESTION: '确定标记所有为已读?',
		ADD_RSS_SOURCE: '添加 RSS 源',
		UPDATE_ALL: '更新全部',
		FETCH_TITLE_TIP: '如果此处为空, 将会一订阅标题替换.',
		NAME: '名称',
		ADDRESS: '地址',
		JANUARY: '一月',
		FEBRUARY: '二月',
		MARCH: '三月',
		APRIL: '四月',
		MAY: '五月',
		JUNE: '六月',
		JULY: '七月',
		AUGUST: '八月',
		SEPTEMBER: '九月',
		OCTOBER: '十月',
		NOVEMBER: '十一月',
		DECEMBER: '十二月',
		MONDAY: '星期一',
		TUESDAY: '星期二',
		WEDNESDAY: '星期三',
		THURSDAY: '星期四',
		FRIDAY: '星期五',
		SATURDAY: '星期六',
		SUNDAY: '星期天',
		TODAY: '今天',
		YESTERDAY: '昨天',
		LAST_WEEK: '最近一周',
		EARLIER_THIS_MONTH: 'Earlier This Month',
		MORE: '更多',
		SETTINGS: '设置',
		EMPTY_TRASH: '清空回收站',
		RSS_FEED_URL: 'RSS 地址: ',
		OPTIONS: '选项',
		UPDATING_FEEDS: '更新中',

		UNREAD: '未读',
		TOTAL: '全部',
		NEW_FOLDER: '新建文件夹',
		DOWNLOAD: '下载',
		DELETE_ALL_ARTICLES: '删除所有文章',
		DELETE_ALL_Q: '确定删除文章?',
		REALLY_EMPTY_TRASH: '确定清空回收站?',
		RENAME: '重命名',
		FOLDER_NAME: '文件夹名'
	}
};

